### ISSUE TITLE
关于招聘

### ISSUE THREAD

**Issue by Leotw** [island205/Lu-Hire#6]
请问陆金所的应聘难度相对BAT要求如何

**Comment by island205** [comment]
没在 BAT 呆过，没法给出回答。

**Comment by yuanchengjs** [comment]
我是一名大三学生，偶然来到了这里，想问下“陆金所”有春招实习生吗？前端方向的话，要求又是怎样的呢？

**Comment by island205** [comment]
@yuancheng1996 招，要求：

1. 比较完整地回答本项目的笔试题
2. 通晓前后端，熟悉 Node.js React 等加分
3. 对前端充满热情，有潜力
